# this file should be called from Debug or Release folder
# it requires tortoiseSVN

for /f "tokens=5" %%i in ('SubWCRev ../../..^|find "Last committed at revision"') do set version=%%i 
if NOT ERRORLEVEL 1 (
echo // auto generated by svnrev.bat > ../../FW_SVN.cs
echo namespace CameraTool >> ../../FW_SVN.cs
echo { >> ../../FW_SVN.cs
echo     public class SofwareRevision >> ../../FW_SVN.cs
echo     { >> ../../FW_SVN.cs
echo 		public int revision = %version%; >> ../../FW_SVN.cs
echo 	} >> ../../FW_SVN.cs
echo } >> ../../FW_SVN.cs
) else (
echo // auto generated by svnrev.bat > ../../FW_SVN.cs
echo // can't get version # from SVN, so assign 9999 > ../FW_SVN.cs
echo namespace CameraTool >> ../../FW_SVN.cs
echo { >> ../../FW_SVN.cs
echo     public class SofwareRevision >> ../../FW_SVN.cs
echo     { >> ../../FW_SVN.cs
echo 		public int revision = 9999; >> ../../FW_SVN.cs
echo 	} >> ../../FW_SVN.cs
echo } >> ../../FW_SVN.cs
)